// <auto-generated />
using System;
using FastMindFinancial.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FastMindFinancial.Migrations
{
    [DbContext(typeof(FastMindFinancialContext))]
    partial class FastMindFinancialContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FastMindFinancial.Model.PedidoCredito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataPrimeiroVencimento");

                    b.Property<int>("QuantidadeParcelas");

                    b.Property<int>("TipoCalculoPeriodo");

                    b.Property<int>("TipoCredito");

                    b.Property<double>("ValorCredito");

                    b.Property<double>("ValorJuros");

                    b.Property<double>("ValorTotalComJuros");

                    b.HasKey("Id");

                    b.ToTable("PedidoCredito");
                });
#pragma warning restore 612, 618
        }
    }
}
